#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

metacity &
nautilus &
gnome-panel &
gnome-settings-daemon &
gnome-terminal &
vncconfig -iconic &
